name: new_task_background_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.14.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sembast: ^3.1.2
  path_provider: ^2.0.8
  uuid: ^3.0.5
  workmanager: ^0.4.0
  intl: ^0.17.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true